# Generated by Django 3.0.8 on 2020-07-21 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='entrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
                ('intro', models.CharField(blank=True, max_length=300)),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('business_pic1', models.ImageField(blank=True, upload_to='bpics')),
                ('business_pic2', models.ImageField(blank=True, upload_to='bpics')),
                ('business_pic3', models.ImageField(blank=True, upload_to='bpics')),
                ('business_pic4', models.ImageField(blank=True, upload_to='bpics')),
                ('business_pic5', models.ImageField(blank=True, upload_to='bpics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
